### ISSUE TITLE
处理速度怎么样？

### ISSUE THREAD

**Issue by xueb96** [fengbaoheng/Pedestrian-detection#1]
我使用C++写的，采用OpenCV自带的HOG+SVM，问题是速度非常慢，请问你的程序效果如何？你知道怎样优化吗？

**Comment by fengbaoheng** [comment]
我用python写的，用HOG和SVM，速度也很慢。正在用C++改写。
想优化的话，我考虑的是：
1. 视频大小压缩一下，把300MB的视频低质量压缩到5MB左右
2. 不需要每一帧都计算，可以间隔6-12帧计算一次
3. 计算前，用鼠标标定出一片ROI区域，缩小计算的范围
